### ISSUE TITLE
Download JavaFX modules sources and JavaDoc

### ISSUE THREAD

**Issue by jperedadnr** [openjfx/javafx-gradle-plugin#1]
Can the plugin download by default the JavaDoc for the required JavaFX modules?
I see it already downloads the sources.

**Comment by jperedadnr** [comment]
You are right, it was IntelliJ. Using command line or NetBeans it doesn't happen.

**Comment by eugener** [comment]
Can be achieved using appropriate IDE plugin. Here is the example 

```
apply plugin: 'java'
apply plugin: 'idea' // or 'eclipse'

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
```
