### ISSUE TITLE
Non-modular support to get rid of JavaFX 16 warning

### ISSUE THREAD

**Issue by ripcurlx** [openjfx/javafx-gradle-plugin#108]
Using the plugin in a non-modular project prints following warning:
```
Unsupported JavaFX configuration: classes were loaded from 'unnamed module @41005828'
```
This is because of https://bugs.openjdk.java.net/browse/JDK-8256362.

Is there a configuration option for the plugin to add the openjfx modules correctly as modules for a non-modular project?

**Comment by abhinayagarwal** [comment]
This is not something which can be handled  via the plugin. The warning comes from JavaFX and as stated in the linked JBS issue, JavaFX should be loaded from moudule-path and not from classpath.
