### ISSUE TITLE
Deprecation warning for Gradle 8.0 in run action

### ISSUE THREAD

**Issue by skht777** [openjfx/javafx-gradle-plugin#114]
In the current stable version, I get warning when I run this.

`.\gradlew run --stacktrace --warning-mode all`

```
The JavaExec.main property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the mainClass property instead. See https://docs.gradle.org/7.2/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:main for more details.
```

It seems the problem of gradle-modules-plugin. Also, in the current version of this plugin, the problem already fixed.

May I fix it and send PR?

**Comment by elliotak47** [comment]
is it resolved ? I'm facing the same.. any suggestions ?

**Comment by skht777** [comment]
Take a look at this.
https://github.com/java9-modularity/gradle-modules-plugin/issues/206
https://github.com/openjfx/javafx-gradle-plugin/pull/120
