### ISSUE TITLE
 How to specify the JavaFX library for downloading MacOS M1 version

### ISSUE THREAD

**Issue by GordonGgx** [openjfx/javafx-gradle-plugin#118]
I found that I am downloading the x64 version of the JavaFX library.
My configuration:
``` groovy
javafx {
  version="17.0.1"
  modules=['javafx.controls','javafx.graphics']
}
```

**Comment by abhinayagarwal** [comment]
This needs an enhancement to the existing plugin.

**Comment by abhinayagarwal** [comment]
It turns out this was already integrated as a part of https://github.com/openjfx/javafx-gradle-plugin/pull/113 and will be available in the next release.

**Comment by abhinayagarwal** [comment]
v0.0.11 is now available with M1 support
