### ISSUE TITLE
3D rendering on JavaFX webview

### ISSUE THREAD

**Issue by tomastiminskas** [openjfx/javafx-gradle-plugin#132]
We are using javafx plugin on a multilatfoprm project to show a web page in a webview. For some reason some pages with 3D canvas are not rendering at all with no error message. Any ideas?

Here is an example of webpage that is not loading:

https://second-brain.sphinx.chat

**Comment by abhinayagarwal** [comment]
As only 3D canvas has an issue with WebView, this is not a plugin issue.
