### ISSUE TITLE
Bump org.javamodularity.moduleplugin version to 1.8.12 to fix Kotlin 1.7+ compatibility

### ISSUE THREAD

**Issue by Tapchicoma** [openjfx/javafx-gradle-plugin#138]
`org.javamodularity.moduleplugin:1.8.12` release [has fixed](https://github.com/java9-modularity/gradle-modules-plugin/releases/tag/v1.8.12) compatibility with Kotlin Gradle Plugin 1.7.0.

Would be nice to bump this dependency in this repo and make a new release. This unblock users to migrate to newer Kotlin versions.

**Comment by miasma** [comment]
Hopefully a new release will appear soon. This seems to block the use of Kotlin 1.7+ (now already at 1.8). The commit https://github.com/openjfx/javafx-gradle-plugin/commit/8debd334eba3729b7d583b586d143618f2df2fba also seems to already fix this so only a new release is needed.

**Comment by dargmuesli** [comment]
@abhinayagarwal would you be able to release a new version by any chance? :raised_hands:

**Comment by raoulsson** [comment]
I really need this so I patched together a temporary fix here: https://github.com/raoulsson/javafx-gradle-plugin. If it works, make sure to switch back to the original, once the next working release is out.

**Comment by abhinayagarwal** [comment]
v0.0.14 is now available
