### ISSUE TITLE
Expose the resolved platform

### ISSUE THREAD

**Issue by aalmiray** [openjfx/javafx-gradle-plugin#17]
The value of the resolved `platform` may be of use to other tasks. Please consider exposing it using the extra properties container, for example

    detectPlatform(project);
    project.ext.platform = platform

**Comment by aalmiray** [comment]
Indeed. I suggest make this a read-only property on the javafx extension class.

**Comment by brunoborges** [comment]
You may as well consider other values such as the specific Linux distribution. This is important for the kind of package to be generated (deb/rpm).

**Comment by aalmiray** [comment]
Agreed. Mentioning that both osdetector and modules plugins are already included and applied should lead people into the right direction.

**Comment by tiainen** [comment]
Yes, I agree with that. That would then be part of #9.
