### ISSUE TITLE
Avoid the usage of afterEvaluate

### ISSUE THREAD

**Issue by JLLeitschuh** [openjfx/javafx-gradle-plugin#19]
The new paradigm for authoring Gradle plugins advises against using `Project::afterEvaluate` because it can unintentionally create plugin application ordering issues.

Instead, plugins should use lazy properties for their tasks/extensions.

You can read more here:
https://docs.gradle.org/current/userguide/lazy_configuration.html

**Comment by jperedadnr** [comment]
Fixed with #44
