### ISSUE TITLE
is Java11 required?

### ISSUE THREAD

**Issue by dieterstueken** [openjfx/javafx-gradle-plugin#2]
I'm about to jump to Java11 but our build server is still on Java10 for the next two weeks.
Thus I hoped to get it temporarily running (or at least compiled) on Java10. 

Unfortunately this plugin (taken from plugins.gradle.org) was compiled by Java11 (class file version 55.0) while FX11 itself seems still on 54.0.

But maybe using JavaFX11 with Java10 does not work anyway.

**Comment by eugener** [comment]
This plugin assumes that JavaFX artifacts (modules) are available from Maven Centra. This started to be the case only with JavaFX 11
