### ISSUE TITLE
Add support to declare modules as `api`

### ISSUE THREAD

**Issue by abhinayagarwal** [openjfx/javafx-gradle-plugin#29]
All dependencies declared via the following block are added as `implementation`:

```
javafx {
    modules 'javafx.graphics'
}
```
There should be a way to declare these dependencies as `api` as well.

**Comment by altavir** [comment]
It was discussed at #5. I am not sure I am fully convinced, but I do not have a lot of experience with modules.

**Comment by SE7-KN8** [comment]
What about the `javafx.base` module? As far as I know, this module doesn't require the native dependencies, which are mentioned in #5.

**Comment by jperedadnr** [comment]
Fixed with #41
