### ISSUE TITLE
Can it be simply named "openjfx"?

### ISSUE THREAD

**Issue by eugener** [openjfx/javafx-gradle-plugin#3]
This way configuration will look like
```
plugins {
    id 'java'
    id 'openjfx' version '0.0.5'
}
```

**Comment by tiainen** [comment]
According to the [documentation](https://guides.gradle.org/publishing-plugins-to-gradle-plugin-portal/#configure_the_plugin_publishing_plugin), the name if the ID should be based on a reverse-domain pattern.

> As a convention, we recommend you use an ID based on the reverse-domain pattern used for Java packages, for example org.example.greeting.
