### ISSUE TITLE
Support to declare modules as `compileOnly`

### ISSUE THREAD

**Issue by jcornaz** [openjfx/javafx-gradle-plugin#37]
Currently, it is only possible to add JavaFx dependency as `implementation` (as already reported by #29 and #11)

There should also be a way to declare the dependency as `compileOnly`. 

With such type of dependency, one could write a library using JavaFX and still publish artifacts not specific to a platform without encountering this kind of problem: #18.

**Comment by mcjp78** [comment]
Made a pull request for this, kinda simple (I hope). #38

**Comment by jperedadnr** [comment]
Fixed with #41
