### ISSUE TITLE
Build fails when using plugin, but it passes when javafx dependencies added manually

### ISSUE THREAD

**Issue by kr5ture** [openjfx/javafx-gradle-plugin#39]
I have encountered following problem with build using `javafx-gradle-plugin`:
```
$ ./gradlew build

> Configure project :
Found module name 'demo.main'

> Task :compileTestJava FAILED
error: the unnamed module reads package com.github.jknack.handlebars.helper from both handlebars.helpers and handlebars
error: the unnamed module reads package javax.activation from both org.apache.sling.javax.activation and activation
error: the unnamed module reads package org.codehaus.groovy.runtime from both org.codehaus.groovy.xml and org.codehaus.groovy
error: the unnamed module reads package groovy.xml from both org.codehaus.groovy.xml and org.codehaus.groovy
error: the unnamed module reads package groovy.util from both org.codehaus.groovy.xml and org.codehaus.groovy
error: module javafx.baseEmpty reads package com.github.jknack.handlebars.helper from both handlebars.helpers and handlebars
error: module javafx.baseEmpty reads package javax.activation from both org.apache.sling.javax.activation and activation
error: module javafx.baseEmpty reads package org.codehaus.groovy.runtime from both org.codehaus.groovy.xml and org.codehaus.groovy
error: module javafx.baseEmpty reads package groovy.xml from both org.codehaus.groovy.xml and org.codehaus.groovy
error: module javafx.baseEmpty reads package groovy.util from both org.codehaus.groovy.xml and org.codehaus.groovy
error: module wiremock reads package com.github.jknack.handlebars.helper from both handlebars.helpers and handlebars
error: module wiremock reads package javax.activation from both org.apache.sling.javax.activation and activation
error: module wiremock reads package org.codehaus.groovy.runtime from both org.codehaus.groovy.xml and org.codehaus.groovy
error: module wiremock reads package groovy.xml from both org.codehaus.groovy.xml and org.codehaus.groovy
error: module wiremock reads package groovy.util from both org.codehaus.groovy.xml and org.codehaus.groovy
// (...) a lot more errors here...
error: module org.xmlunit reads package groovy.util from both org.codehaus.groovy.xml and org.codehaus.groovy
100 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
3 actionable tasks: 3 executed
```

My application fetches data from some external services which are mocked using `wiremock` within tests. Gradle configuration [here](https://github.com/kr5ture/javafx-gradle-plugin-issue/blob/gradle-with-plugin/build.gradle). Build passes once either I remove `javafx` plugin or `wiremock` dependency.

I have tested various build configuration and here are the results:

Build configuration | Configuration file | Result
---|---|---
Gradle with plugin | [build.gradle](https://github.com/kr5ture/javafx-gradle-plugin-issue/blob/gradle-with-plugin/build.gradle) | Build fails due to error above
Gradle without plugin (dependencies added manually) | [build.gradle](https://github.com/kr5ture/javafx-gradle-plugin-issue/blob/gradle-without-plugin/build.gradle) | Build passes
Maven with plugin | [pom.xml](https://github.com/kr5ture/javafx-gradle-plugin-issue/blob/maven-with-plugin/pom.xml) | Build passes

Following example project is affected by the issue: https://github.com/kr5ture/javafx-gradle-plugin-issue/tree/gradle-with-plugin . I created three branches with build configurations by the table above.

**Comment by folterj** [comment]
Same experience:
- Using org.openjfx.javafxplugin as documented on main page works but resulting JAR does not include any openjfx packages
- Without plugin, just adding openjfx as dependencies works AND resulting jar will include openjfx packages

Environment: Windows 10, Eclipse, Gradle (Buildship plugin)

**Comment by jperedadnr** [comment]
@kr5ture Actually your issue has to do with the modular [plugin](https://github.com/java9-modularity/gradle-modules-plugin) that the JavaFX gradle plugin uses. It has nothing to do with JavaFX either. In fact, if you add the `application` plugin, the `run` task works fine with your use case. 

I'd suggest you file an issue [here](https://github.com/java9-modularity/gradle-modules-plugin/issues), with a use case similar to the ones you have at https://github.com/kr5ture/javafx-gradle-plugin-issue/, but removing the JavaFX part, and using instead:
```
plugins {
	id 'org.javamodularity.moduleplugin' version '1.5.0'
}
``` 

@folterj Your issue has nothing to do with the one at hand. Feel free to file a new issue with enough details to reproduce it, but check out first the documentation on how to distribute your projects at https://openjfx.io/openjfx-docs/#modular, Gradle sections.
