### ISSUE TITLE
android mandatory 64 bit architecture!

### ISSUE THREAD

**Issue by janko33bd** [openjfx/javafx-gradle-plugin#40]
Starting **August 1, 2019**, your apps published on Google Play will need to support 64-bit architectures. 64-bit CPUs deliver faster, richer experiences for your users. Adding a 64-bit version of your app provides performance improvements, makes way for future innovation, and sets you up for devices with 64-bit-only hardware.

https://developer.android.com/distribute/best-practices/develop/64-bit

Currently there is no way to rellease your application to Google Play.
uploading apk after apkRelease, zipalignRelease gives you this:
![image](https://user-images.githubusercontent.com/10329950/59535248-c03c8e00-8ef0-11e9-8a71-67c2f2044236.png)

**Comment by jperedadnr** [comment]
This plugin has nothing to do with Android apps
