### ISSUE TITLE
Support transitive module dependencies

### ISSUE THREAD

**Issue by altavir** [openjfx/javafx-gradle-plugin#5]
Suppose I have multi-project build where `A` is a base and `B` and `C` depends on it. 'A' is a library and does not include `application` plugin, but `B` and `C` do have main class etc. Currently, if I apply plugin to `A`, then everything works fine in compile time, but I am missing FX runtime for `B` and `C`. Is it possible to make runtime libraries transitive?

**Comment by tiainen** [comment]
The dependencies to the JavaFX modules can not be made transitive, because they are platform dependent. Hence, you need to apply this plugin to each project that uses JavaFX.

In case you have a multi-project setup, you can write common code inside `allprojects`, for example:

    allprojects {
        javafx {
            modules = [ 'javafx.controls' ]
        }
    }
