### ISSUE TITLE
How to create Windows executables(Exe) files from this Plugin

### ISSUE THREAD

**Issue by hashweather** [openjfx/javafx-gradle-plugin#52]
Hi,

I have followed the instructions to add this plugin to my build.gradle file.

Now I am done with my JavaFX Application and I wish to package the final application as an executable .exe file for the Windows Platform  . How can I do that? Thanks.

**Comment by abhinayagarwal** [comment]
Creating OS specific packages is out of scope of this plugin.

Please checkout [badass-jlink-plugin](https://github.com/beryx/badass-jlink-plugin) which uses [jpackage](https://jdk.java.net/jpackage/) for the same.
