### ISSUE TITLE
Gradle: as soon as javafxplugin is used, classpath of the corresponding module gets erased

### ISSUE THREAD

**Issue by elect86** [openjfx/javafx-gradle-plugin#58]
As titled, if I `assemble` with the plugin:

```
plugins {   
    ...
    id 'org.openjfx.javafxplugin' version '0.0.8'
}
```

Then my `classPath` is completely empty

```
compileJava {
    inputs.property("moduleName", moduleName)
    doFirst {
        println("[$moduleName]classpath.asPath: $classpath.asPath") // nothing
        options.compilerArgs = ['--module-path', classpath.asPath,]
        classpath = files()
    }
}
```

and then the modules are not found (JPMS)

`build.gradle` and module [here](https://github.com/kotlin-graphics/imgui/blob/master/imgui-openjfx/build.gradle)

This seems to be a valid workaround atm:
```
def currentOS = org.gradle.internal.os.OperatingSystem.current()
def platform
if (currentOS.isWindows()) {
    platform = 'win'
} else if (currentOS.isLinux()) {
    platform = 'linux'
} else if (currentOS.isMacOsX()) {
    platform = 'mac'
}
dependencies {
    compile "org.openjfx:javafx-base:11:${platform}"
    compile "org.openjfx:javafx-graphics:11:${platform}"
    compile "org.openjfx:javafx-controls:11:${platform}"
    compile "org.openjfx:javafx-fxml:11:${platform}"
}
```

**Comment by jperedadnr** [comment]
Does it happen with plugin version 0.0.7?

Note that the plugin uses `implementation` instead of the deprecated `compile`, and therefore some configurations are not used anymore. `configuration.runtimeClasspath` should work now (see https://stackoverflow.com/questions/57452363/building-fatjar-for-javafx-with-gradle-and-intellij-getting-noclassdeffounderro/)-

**Comment by elect86** [comment]
Sorry Josè, I never went further and now I completely dropped javaFx for the moment

If you want, close it
