### ISSUE TITLE
Project with transitive dependency on newer version of JavaFX fails

### ISSUE THREAD

**Issue by abhinayagarwal** [openjfx/javafx-gradle-plugin#69]
Consider a scenario where a project with `javafx-gradle-plugin` is trying to use version 11 for JavaFX modules and it also has a dependency on ControlsFX 11.0.2.

```
javafx {
    version = "11"
    modules = [ 'javafx.controls' ]
}

dependencies {
      compile 'org.controlsfx:controlsfx:11.0.1'
}
```

In this case the project will fail to run. ControlsFX introduces a transitive dependency to JavaFX 11.0.2 and since classpath always uses the latest version, the plugin fails to find JavaFX modules with version 11 on the classpath.

This can be fixed by doing a version-less comparison while adding JavaFX modules to module-path from the classpath.

**Comment by danielpeintner** [comment]
Mhh, doesn't it help to exclude the transitive dependency? Or do I misunderstand the issue?

```
dependencies {
    compile ('org.controlsfx:controlsfx:11.0.1') {
        exclude group: 'org.openjfx', module: '*'
    }
}
```

**Comment by abhinayagarwal** [comment]
If you run  `./gradlew run` on a project with the `javafx + dependencies` block in issue description, you will find the following:

* --add-modules: has correct parameters
* --module-path: empty
*  --cp: has correct parameters including all JavaFX dependencies

The empty module-path causes the application to fail without throwing any suggestion on what went wrong. 

@danielpeintner As you said, this can be fixed by excluding all transitive JavaFX dependencies. But, shouldn't there be a better way to handle it? PR #70 is my attempt to find it :)
