### ISSUE TITLE
JavaFX plugin implicitly puts all code on the module path instead of the classpath

### ISSUE THREAD

**Issue by dgelessus** [openjfx/javafx-gradle-plugin#7]
Currently the JavaFX plugin implicitly applies the module plugin (https://github.com/java9-modularity/gradle-modules-plugin):
https://github.com/openjfx/javafx-gradle-plugin/blob/c4b1ae0f01940090e309319ce1040d4b91841c39/src/main/java/org/openjfx/gradle/JavaFXPlugin.java#L35
This automatically puts the entire project and its dependencies on the module path rather than the classpath, which is problematic when porting an existing project to Java 11/OpenJFX. (In my case for example I have some dependencies with conflicting package names, i. e. "split packages", which makes them incompatible with the module system.)

This behavior is quite surprising, since the README never mentions modularization anywhere. The [guides](https://openjfx.io/openjfx-docs/) on openjfx.io explain how to create "[non-modular](https://openjfx.io/openjfx-docs/#IDEA-Gradle)" and "[modular](https://openjfx.io/openjfx-docs/#IDEA-Mod-Gradle)" OpenJFX applications using the Gradle plugin, but as far as I can tell even the "non-modular" version uses the module system at runtime (it just doesn't have a module-info.java).

I'm not all that familiar with the module system yet, but from what I've read it is possible to use both the classpath (for non-modular code) and the module path (for modular code) at the same time. In that case, shouldn't it be possible to put OpenJFX on the module path without affecting all of the project code and the dependencies?

In any case, it would be helpful if the documentation explained in what way the module system is used/required, and in particular whether the project code needs to be modularized before it can use OpenJFX.

**Comment by tiainen** [comment]
See the following issue in the gradle modules plugin: https://github.com/java9-modularity/gradle-modules-plugin/issues/47

**Comment by Xerus2000** [comment]
The gradle modules plugin has been updated, but I still see classpath conflict issues when using this plugin. I guess you have to release a new version?
