### ISSUE TITLE
Error in Intellij

### ISSUE THREAD

**Issue by dprutean** [openjfx/javafx-gradle-plugin#81]
I started a small JavaFx app with the build.grade like here

Still, when I want to execute the main class I get:
java.lang.IllegalAccessError: superclass access check failed: class com.sun.javafx.scene.control.ControlHelper (in unnamed module @0x117c7d50) cannot access class com.sun.javafx.scene.layout.RegionHelper (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.scene.layout to unnamed module @0x117c7d50

Project is set to use OpenJDK11, Gradle 6.5. 
Do you know any way to fix this ?

```
plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '8.8.2'
}

repositories {
    mavenCentral()
}

javafx {
    version = "14"
    modules = [ 'javafx.controls', 'javafx.graphics' ]
}

mainClassName = 'CustomTextAreaApp'
```

**Comment by altavir** [comment]
Where did you get the version from? The latest version of a plugin is `0.0.8` at the moment. The gradle build should just fail for you. You are probably trying to run your application via IDEA runner.

**Comment by dprutean** [comment]
You are right, I was using 0.0.8 before and fixed later to 8.8.2 ( I found it in maven central). 
Now I turned back to 0.0.8.
If I execute the gradle task 'jar' it works fine.
But the runner in Intellij is failing. Do you know how may I fix this?

**Comment by altavir** [comment]
@dprutean 
![image](https://user-images.githubusercontent.com/9514268/84994796-e4f6c180-b153-11ea-984a-b58e8f1aa470.png)
Also you can just run gradle sync and build from the menu, but it is recommended to use gradle runner.

**Comment by dprutean** [comment]
Thank you very much for help. I think I still miss something:




    On Thursday, June 18, 2020, 10:08:55 AM GMT+2, Alexander Nozik <notifications@github.com> wrote:  
 
 


@dprutean

Also you can just run gradle sync and build from the menu, but it is recommended to use gradle runner.

**Comment by abhinayagarwal** [comment]
> java.lang.IllegalAccessError: superclass access check failed: class com.sun.javafx.scene.control.ControlHelper (in unnamed module @0x117c7d50) cannot access class com.sun.javafx.scene.layout.RegionHelper (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.scene.layout to unnamed module @0x117c7d50

This means you need to add the following to your `jvmArgs`:

```
run {
    jvmArgs = [
           '--add-export=javafx.graphics/com.sun.javafx.scene.layout=ALL-UNNAMED'
    ]
}
```
