### ISSUE TITLE
how to download specific fx version and platform?

### ISSUE THREAD

**Issue by josephstgh** [openjfx/javafx-gradle-plugin#82]
Hi, I'm trying to download specific version of javafx modules

I'm using `gradle 6.5` and this is my `build.gradle`. Note, I'm using `nexus` as a proxy but this shouldn't matter.

```
plugins {
    // Apply the java-library plugin to add support for Java Library
    id 'java-library'
    id 'eclipse'
    id 'org.openjfx.javafxplugin' version'0.0.8'
    id 'org.springframework.boot' version '2.3.1.RELEASE'
	id 'io.spring.dependency-management' version '1.0.9.RELEASE'
	id 'io.freefair.lombok' version '5.1.0'
}

repositories {
	maven {
		url "${nexusUrl}/repository/mvn-group/"
	}
}

javafx {
	version = '14.01'
	modules = [ 'javafx.base', 'javafx.controls', 'javafx.fxml', 'javafx.graphics', 'javafx.media', 'javafx.swing', 'javafx.web' ]
    // configuration = 'compileOnly'
}
```

It will complain this

![image](https://user-images.githubusercontent.com/47846485/85001699-90b90500-b186-11ea-81e3-ceeebba76f6e.png)

It will work if I change to `14` instead of `14.01`. `14.01` does exist in [mvnrepo](https://mvnrepository.com/artifact/org.openjfx/javafx-base)

I also wish to download for a specific platform, or rather, I would like to download all type of platforms available. I tried to add `configuration = 'compileOnly'` but it doesn't seem to work. Is there a config for me to set to download by platform? I tried to look through the issues, but don't seem to find any.

Thanks!

**Comment by DJViking** [comment]
The version is `14.0.1`.

**Comment by josephstgh** [comment]
Ah!

My bad.. thanks for the correction.

It also seem like it does auto download different platforms jar.

Thanks!
