### ISSUE TITLE
Do not hard-code the default JavaFX version

### ISSUE THREAD

**Issue by sschuberth** [openjfx/javafx-gradle-plugin#86]
Instead of doing

https://github.com/openjfx/javafx-gradle-plugin/blob/e03fb27aedfdf85bca7d98fce474e6ce609201e4/src/main/java/org/openjfx/gradle/JavaFXOptions.java#L51

it seems more reasonable to me to do something like

    private String version = JavaVersion.current().majorVersion

**Comment by abhinayagarwal** [comment]
It was hardcoded because we wanted to use the latest version of JavaFX irrespective of the Java version used.

**Comment by sschuberth** [comment]
But arbitrarily mixing the JavaFX version with a different Java version potentially leads to compile errors. I cannot recall the exact error message right now, but I believe I was unable to use Java 11 this way.

**Comment by abhinayagarwal** [comment]
All JavaFX versions after 11 is compatible with Java 11+. If you find a compatibility issue with any version, please report.

**Comment by sschuberth** [comment]
I can't reproduce the issue anymore right now, but I still believe it could make sense to do something like

    version = 11.coerceAtLeast(JavaVersion.current().majorVersion.toInt()).toString()

(in Kotlin DSL syntax) here.
