### ISSUE TITLE
win-per-user-install causes Error

### ISSUE THREAD

**Issue by KenobySky** [openjfx/javafx-gradle-plugin#87]
When installing my application using win-per-user-install, it generates this error:

Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object

When I dont use win-per-user-install, it works as intended. 

Reinstalled all JDK's, reinstalled all JRE's, reverted all commits, but cant find the issue. 

Is it a security problem?

**Comment by KenobySky** [comment]
I investigated the issue further. The issue only happens on my computer. And the error only happens when the application is running from the temp folder.

**Comment by abhinayagarwal** [comment]
This seems to be related to JPackage which is not handled by this plugin.
