### ISSUE TITLE
run error in jpms and gradle 6.6

### ISSUE THREAD

**Issue by MakHoCheung** [openjfx/javafx-gradle-plugin#89]
My demo project uses gradle 6.6 , jpms structruce and  javafxplugin 0.0.9. When I run then run task, an error occurs as follow
```
> org.joor.ReflectException: java.lang.NoSuchFieldException: javaExecHandleBuilder
```

If I change the gradle version to 6.5 or remove the module-info.java, the run task works fine

**Comment by jperedadnr** [comment]
Related to https://github.com/java9-modularity/gradle-modules-plugin/issues/165

**Comment by utybo** [comment]
Can confirm that this is affecting me as well and makes the JavaFX plugin unusable for Gradle 6.6+. Any workarounds?

**Comment by MakHoCheung** [comment]
Here is a simple way to configure a module JavaFx project in Gradle 6.6.
1
```
java {
    modularity.inferModulePath.set(true)
}
```
2
```
application{
    mainModule.set($moduleName)
    mainClass.set($mainClass)
}
```
3
```
dependencies {
    val jfxOptions = object {
        val group = "org.openjfx"
        val version = "14.0.2.1"
        val fxModules = arrayListOf("javafx-base","javafx-controls","javafx-graphics","javafx-media","javafx-swing")
    }
    jfxOptions.run {
        val osName = System.getProperty("os.name")
        val platform = when {
            osName.startsWith("Mac", ignoreCase = true) -> "mac"
            osName.startsWith("Windows", ignoreCase = true) -> "win"
            osName.startsWith("Linux", ignoreCase = true) -> "linux"
            else -> ""
        }
        fxModules.forEach {
            implementation("$group:$it:$version:$platform")
        }
    }
}

```

**Comment by jchildress** [comment]
Any update on this?  I'm getting the same "error"...  

> org.joor.ReflectException: java.lang.NoSuchFieldException: javaExecHandleBuilder

**Comment by xzel23** [comment]
Ok, so I looked into this again because I want to try building JavaFX applications on JDK 16. This will require Gradle 7. I saw that this plugin has a dependency on a plugin to help with the module system (org.javamodularity.moduleplugin). This won't be needed on Gradle 7+ because Gradle 7 will come with full support for Jigsaw modules.

So I have forked this module on Github to experiment with this, and now I have a working plugin for Gradle 7/JDK 16 that runs my example project perfectly fine.

If anyone is interested in trying it out, please let me know. I think it might not (yet?) be a good idea to merge back into upstream because it will break things for those using older Gradle versions.

**Comment by bjonnh** [comment]
I would like to give it a try. I need to build an application for both windows and Linux and it is quite painful… I was trying to switch to github actions to build them remotely but I keep hitting on different issues. Now it is the: 
```
> Failed to apply plugin class 'org.javamodularity.moduleplugin.ModuleSystemPlugin'.
   > Could not create task ':run'.
      > Replacing an existing task that may have already been used by other plugins is not supported.  Use a different name for this task ('run').

```

**Comment by xzel23** [comment]
@bjonnh: my Gradle 7 compatible fork of the plugin is at https://github.com/xzel23/javafx-gradle-plugin. I have also just submitted it for inclusion in the Gradle plugin catalogue, but it's still pending approval. I will leave a comment here if it is available via the standard Gradle plugin repository. I have tested it with Gradle 7 Milestone 3 and JDK 16.

**Comment by xzel23** [comment]
The forked plugin for Gradle 7 is now [available](https://plugins.gradle.org/plugin/com.dua3.javafxgradle7plugin). I hope it works for you. If it doesn't, remember not to report issues here but in the fork. If I find the time, I might at some later time try to find a solution that doesn't break builds on Gradle 6 and could be applied upstream.

**Comment by patilnikhilh80** [comment]
> Ok, so I looked into this again because I want to try building JavaFX applications on JDK 16. This will require Gradle 7. I saw that this plugin has a dependency on a plugin to help with the module system (org.javamodularity.moduleplugin). This won't be needed on Gradle 7+ because Gradle 7 will come with full support for Jigsaw modules.
> 
> So I have forked this module on Github to experiment with this, and now I have a working plugin for Gradle 7/JDK 16 that runs my example project perfectly fine.
> 
> If anyone is interested in trying it out, please let me know. I think it might not (yet?) be a good idea to merge back into upstream because it will break things for those using older Gradle versions.

I used your fork in my project but I am getting error 
src\main\java\module-info.java:6: error: module not found: jettison
requires jettison;

Do I need to change some configuration to add this dependancy?

**Comment by xzel23** [comment]
@patilnikhilh80 This looks like a problem with your build that has nothing to do with the gradle plugin. I have never used jettison, so I looked for the project on github. At first glance, it seems not to offer any support for the module system, not even an automatic module name. If that's right, please open an issue with the jettison maintainers to request [module support](https://www.javaadvent.com/2017/12/automatic-module-name-calling-java-library-maintainers.html).
