### ISSUE TITLE
Kotlin not working: java.lang.module.FindException: Module MY_MODULE not found

### ISSUE THREAD

**Issue by gringofe** [openjfx/javafx-gradle-plugin#91]
Hello,

when I update from version `0.0.8` to `0.0.9`, my run task aborts with `Error occurred during initialization of boot layer
java.lang.module.FindException: Module MY_MODULE not found` where `MY_MODULE` is, as you might have already guessed, my module, which I defined in `module-info`. I'm using Gradle `6.0`, and Java/JavaFX `11`

**Comment by abhinayagarwal** [comment]
Can you post your build script? Can you replicate the issue in one of [our samples](https://github.com/openjfx/samples)?

**Comment by gringofe** [comment]
Hello,

sorry for the late reply, but I think I found the problem: Kotlin.
When I bump the `javafx-gradle-plugin` version to `0.0.9` and add `id "org.jetbrains.kotlin.jvm" version "1.4.0"` to the `plugin` part of the [IntelliJ Modular Gradle sample](https://github.com/openjfx/samples/blob/master/IDE/IntelliJ/Modular/Gradle/hellofx/build.gradle), the exception above occurs.

**Comment by gringofe** [comment]
Okay, adding kotlin before the javafxplugin fixes the issue as can be seen [here](https://github.com/beryx-gist/badass-jlink-example-kotlin-javafx/blob/master/build.gradle.kts)
