### ISSUE TITLE
Build app for specific platform

### ISSUE THREAD

**Issue by markowanga** [openjfx/javafx-gradle-plugin#92]
I want to build apps for Windows, Mac and Linux -- is it possible to build it with this plugin?
I know about third-party apps, but I want use gradle if it is possible (it will be easy to use in CI/CD).

**Comment by abhinayagarwal** [comment]
Please checkout https://github.com/beryx/badass-runtime-plugin/ and https://github.com/beryx/badass-jlink-plugin
