### ISSUE TITLE
Support for gradle 6.7

### ISSUE THREAD

**Issue by UltraBurstXD** [openjfx/javafx-gradle-plugin#93]

**Comment by a-dudko** [comment]
Is it also necessary for toolchain support?

**Comment by UltraBurstXD** [comment]
I think so... All my projects built with javafx gradle plugin won't run. So, they are likely toys...

**Comment by UltraBurstXD** [comment]
There is a PR, #79, anyway things here seems like abandoned. I thought it would be available in 0.0.10-SNAPSHOT.

**Comment by UltraBurstXD** [comment]
Guess the only way out is download and build it myself.
