### ISSUE TITLE
How to export with JavaFx dependencies

### ISSUE THREAD

**Issue by Xamez** [openjfx/javafx-gradle-plugin#97]
Hey, I just finished what I had to do but I can't find a way to export my jar with JavaFx, do you have an idea?
Here's my build.gradle:
![image](https://user-images.githubusercontent.com/35816109/115607110-d7b2e200-a2e4-11eb-9a20-b83330746688.png)

**Comment by chirontt** [comment]
Your problem is about the Gradle build script itself, not about the JavaFX plugin.

I'm not sure this is the appropriate forum to resolve some Gradle script problem.

**Comment by Xamez** [comment]
Where can I go? And as written in the title, it is a question :/

**Comment by abhinayagarwal** [comment]
Go through [Non-Modular project -> Gradle](https://openjfx.io/openjfx-docs/#Non-Mod). The sections describes how you can create a FAT JAR with JavaFX dependencies.
